<a href="https://colab.research.google.com/github/songthao1610/Map-Modelling---Project-1/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE

# New Section

In [17]:
data = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [18]:
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [19]:
data.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [20]:
data['bmi'] = data['bmi'].fillna(data['bmi'].mean())

In [51]:
data['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [21]:
data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [22]:
for feature in data.columns:
  print(f'{feature}:', data[feature].unique())

id: [ 9046 51676 31112 ... 19723 37544 44679]
gender: ['Male' 'Female' 'Other']
age: [6.70e+01 6.10e+01 8.00e+01 4.90e+01 7.90e+01 8.10e+01 7.40e+01 6.90e+01
 5.90e+01 7.80e+01 5.40e+01 5.00e+01 6.40e+01 7.50e+01 6.00e+01 5.70e+01
 7.10e+01 5.20e+01 8.20e+01 6.50e+01 5.80e+01 4.20e+01 4.80e+01 7.20e+01
 6.30e+01 7.60e+01 3.90e+01 7.70e+01 7.30e+01 5.60e+01 4.50e+01 7.00e+01
 6.60e+01 5.10e+01 4.30e+01 6.80e+01 4.70e+01 5.30e+01 3.80e+01 5.50e+01
 1.32e+00 4.60e+01 3.20e+01 1.40e+01 3.00e+00 8.00e+00 3.70e+01 4.00e+01
 3.50e+01 2.00e+01 4.40e+01 2.50e+01 2.70e+01 2.30e+01 1.70e+01 1.30e+01
 4.00e+00 1.60e+01 2.20e+01 3.00e+01 2.90e+01 1.10e+01 2.10e+01 1.80e+01
 3.30e+01 2.40e+01 3.40e+01 3.60e+01 6.40e-01 4.10e+01 8.80e-01 5.00e+00
 2.60e+01 3.10e+01 7.00e+00 1.20e+01 6.20e+01 2.00e+00 9.00e+00 1.50e+01
 2.80e+01 1.00e+01 1.80e+00 3.20e-01 1.08e+00 1.90e+01 6.00e+00 1.16e+00
 1.00e+00 1.40e+00 1.72e+00 2.40e-01 1.64e+00 1.56e+00 7.20e-01 1.88e+00
 1.24e+00 8.00e-01 4.00e-01 8.00e-02 1.48e+00 5.60e-01 4.80e-01 1.60e-01]
hypertension: [0 1]
heart_disease: [1 0]
ever_married: ['Yes' 'No']
work_type: ['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']
Residence_type: ['Urban' 'Rural']
avg_glucose_level: [228.69 202.21 105.92 ...  82.99 166.29  85.28]
bmi: [36.6        28.89323691 32.5        34.4        24.         29.
 27.4        22.8        24.2        29.7        36.8        27.3
 28.2        30.9        37.5        25.8        37.8        22.4
 48.9        26.6        27.2        23.5        28.3        44.2
 25.4        22.2        30.5        26.5        33.7        23.1
 32.         29.9        23.9        28.5        26.4        20.2
 33.6        38.6        39.2        27.7        31.4        36.5
 33.2        32.8        40.4        25.3        30.2        47.5
 20.3        30.         28.9        28.1        31.1        21.7
 27.         24.1        45.9        44.1        22.9        29.1
 32.3        41.1        25.6        29.8        26.3        26.2
 29.4        24.4        28.         28.8        34.6        19.4
 30.3        41.5        22.6        56.6        27.1        31.3
 31.         31.7        35.8        28.4        20.1        26.7
 38.7        34.9        25.         23.8        21.8        27.5
 24.6        32.9        26.1        31.9        34.1        36.9
 37.3        45.7        34.2        23.6        22.3        37.1
 45.         25.5        30.8        37.4        34.5        27.9
 29.5        46.         42.5        35.5        26.9        45.5
 31.5        33.         23.4        30.7        20.5        21.5
 40.         28.6        42.2        29.6        35.4        16.9
 26.8        39.3        32.6        35.9        21.2        42.4
 40.5        36.7        29.3        19.6        18.         17.6
 19.1        50.1        17.7        54.6        35.         22.
 39.4        19.7        22.5        25.2        41.8        60.9
 23.7        24.5        31.2        16.         31.6        25.1
 24.8        18.3        20.         19.5        36.         35.3
 40.1        43.1        21.4        34.3        27.6        16.5
 24.3        25.7        21.9        38.4        25.9        54.7
 18.6        24.9        48.2        20.7        39.5        23.3
 64.8        35.1        43.6        21.         47.3        16.6
 21.6        15.5        35.6        16.7        41.9        16.4
 17.1        29.2        37.9        44.6        39.6        40.3
 41.6        39.         23.2        18.9        36.1        36.3
 46.5        16.8        46.6        35.2        20.9        13.8
 31.8        15.3        38.2        45.2        17.         49.8
 27.8        60.2        23.         22.1        26.         44.3
 51.         39.7        34.7        21.3        41.2        34.8
 19.2        35.7        40.8        24.7        19.         32.4
 34.         28.7        32.1        51.5        20.4        30.6
 71.9        19.3        40.9        17.2        16.1        16.2
 40.6        18.4        21.1        42.3        32.2        50.2
 17.5        18.7        42.1        47.8        20.8        30.1
 17.3        36.4        12.         36.2        55.7        14.4
 43.         41.7        33.8        43.9        22.7        57.5
 37.         38.5        16.3        44.         32.7        54.2
 40.2        33.3        17.4        41.3        52.3        14.6
 17.8        46.1        33.1        18.1        43.8        50.3
 38.9        43.7        39.9        15.9        19.8        12.3
 78.         38.3        41.         42.6        43.4        15.1
 20.6        33.5        43.2        30.4        38.         33.4
 44.9        44.7        37.6        39.8        53.4        55.2
 42.         37.2        42.8        18.8        42.9        14.3
 37.7        48.4        50.6        46.2        49.5        43.3
 33.9        18.5        44.5        45.4        55.         54.8
 19.9        17.9        15.6        52.8        15.2        66.8
 55.1        18.2        48.5        55.9        57.3        10.3
 14.1        15.7        56.         44.8        13.4        51.8
 38.1        57.7        44.4        38.8        49.3        39.1
 54.         56.1        97.6        53.9        13.7        11.5
 41.4        14.2        49.4        15.4        45.1        49.2
 48.7        53.8        42.7        48.8        52.7        53.5
 50.5        15.8        45.3        14.8        51.9        63.3
 40.7        61.2        48.         46.8        48.3        58.1
 50.4        11.3        12.8        13.5        14.5        15.
 59.7        47.4        52.5        13.2        52.9        61.6
 49.9        54.3        47.9        13.         13.9        50.9
 57.2        64.4        92.         50.8        57.9        45.8
 47.6        14.         46.4        46.9        47.1        13.3
 48.1        51.7        46.3        54.1        14.9       ]
smoking_status: ['formerly smoked' 'never smoked' 'smokes' 'Unknown']
stroke: [1 0]

In [41]:
df = data.copy()
bins = [0, 18, 30, 40, 50, 100]  # Define the edges of the bins
labels = ['0-18', '19-30', '31-40', '41-50', '51+']  # Labels for the bins
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

In [42]:
df['age_group']

0         51+
1         51+
2         51+
3       41-50
4         51+
        ...
5105      51+
5106      51+
5107    31-40
5108      51+
5109    41-50
Name: age_group, Length: 5110, dtype: category
Categories (5, object): ['0-18' < '19-30' < '31-40' < '41-50' < '51+']

In [58]:
label_encoder = LabelEncoder()

cat_columns = ['gender','ever_married','work_type','Residence_type','smoking_status','age_group']
for column in cat_columns:
    df[column] = label_encoder.fit_transform(df[column])

Y = df['stroke']
X = df.drop(columns = ['stroke','id','age'])
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
# Initialize SMOTE
smote = SMOTE(random_state=42)

# Fit and apply SMOTE to the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [59]:
X_train_resampled

,gender,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,age_group
0,1,0,0,0,4,0,90.420000,16.200000,0,0
1,1,0,0,0,2,1,207.580000,22.800000,3,1
2,1,1,0,1,2,0,91.280000,26.500000,2,3
3,0,1,0,1,2,1,150.740000,40.300000,0,4
4,0,0,0,1,2,0,82.570000,36.000000,1,4
...,...,...,...,...,...,...,...,...,...,...
6829,1,0,0,0,1,0,217.896120,28.320992,0,4
6830,1,1,0,1,2,0,247.301388,27.934177,2,4
6831,0,0,1,0,2,0,60.668965,29.473962,1,4
6832,0,0,0,1,1,1,110.723110,25.791870,0,4
6833,0,1,0,0,1,0,70.518475,35.446860,2,4

In [63]:

classifiers = {
    'Logistic Regression': LogisticRegression(max_iter=500),
    'Random Forest': RandomForestClassifier()}
param_grid = {
    'Logistic Regression': {'C': [0.1, 1, 10]},
    'Random Forest': {'n_estimators': [10, 50, 100], 'max_depth': [ 10, 20]}

}

best_estimators = {}

for clf_name, clf in classifiers.items():
    print(f"Performing GridSearchCV for {clf_name}...")

    # Use GridSearchCV for parameter tuning
    grid_search = GridSearchCV(clf, param_grid[clf_name], cv=5, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train_resampled, y_train_resampled)

    # Store the best estimator
    best_estimators[clf_name] = grid_search.best_estimator_

    # Evaluate on test data
    y_pred = grid_search.best_estimator_.predict(X_test)
    print(f"Best Model for {clf_name}: {grid_search.best_params_}")
    print(f"Accuracy for {clf_name}: {accuracy_score(y_test, y_pred)}")
    print(f"Classification Report for {clf_name}:\n{classification_report(y_test, y_pred)}")

    print("-" * 50)
best_model_name = max(best_estimators, key=lambda clf: accuracy_score(y_test, best_estimators[clf].predict(X_test)))
print(f"Overall best model: {best_model_name}")

Performing GridSearchCV for Logistic Regression...
Best Model for Logistic Regression: {'C': 0.1}
Accuracy for Logistic Regression: 0.7195042400521853
Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.97      0.73      0.83      1444
           1       0.12      0.57      0.19        89

    accuracy                           0.72      1533
   macro avg       0.54      0.65      0.51      1533
weighted avg       0.92      0.72      0.79      1533

--------------------------------------------------
Performing GridSearchCV for Random Forest...
Best Model for Random Forest: {'max_depth': 20, 'n_estimators': 50}
Accuracy for Random Forest: 0.8793215916503587
Classification Report for Random Forest:
              precision    recall  f1-score   support

           0       0.95      0.92      0.93      1444
           1       0.15      0.22      0.18        89

    accuracy                           0.88      1533
   macro avg       0.55      0.57      0.56      1533
weighted avg       0.90      0.88      0.89      1533

--------------------------------------------------
Overall best model: Random Forest